### ISSUE TITLE
Error running the example file

### ISSUE THREAD

**Issue by esimov** [chai2010/libfacedetection-go#1]
I'm unable to test the example, because i'm getting the following error:

OS: Ubuntu 16.04

```bash
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x7fd996ff4010 pc=0x4bd965]

runtime stack:
runtime.throw(0x50a8a0, 0x2a)
	/usr/lib/go-1.10/src/runtime/panic.go:616 +0x81
runtime.sigpanic()
	/usr/lib/go-1.10/src/runtime/signal_unix.go:372 +0x28e

goroutine 1 [syscall]:
runtime.cgocall(0x4bd6e0, 0xc42005fde0, 0xc42005fe08)
	/usr/lib/go-1.10/src/runtime/cgocall.go:128 +0x64 fp=0xc42005fdb0 sp=0xc42005fd78 pc=0x405274
github.com/chai2010/libfacedetection-go._Cfunc_libfacedetection_capi_result_len(0x7fd996ff4010, 0x7fd900000000)
	_cgo_gotypes.go:111 +0x49 fp=0xc42005fde0 sp=0xc42005fdb0 pc=0x4bc699
github.com/chai2010/libfacedetection-go.DetectFaceRGB.func1(0x7fd996ff4010, 0x1e000000280)
	/home/esimov/Projects/Go/src/github.com/chai2010/libfacedetection-go/libfacedetection.go:68 +0x56 fp=0xc42005fe18 sp=0xc42005fde0 pc=0x4bcb46
github.com/chai2010/libfacedetection-go.DetectFaceRGB(0xc42013c000, 0xe1000, 0xe1000, 0x280, 0x1e0, 0x780, 0x1e0, 0xc4200ba000, 0xc42005f57b)
	/home/esimov/Projects/Go/src/github.com/chai2010/libfacedetection-go/libfacedetection.go:68 +0x77 fp=0xc42005fe90 sp=0xc42005fe18 pc=0x4bc757
main.main()
	/home/esimov/Projects/Go/src/github.com/chai2010/libfacedetection-go/hello.go:26 +0xaf fp=0xc42005ff88 sp=0xc42005fe90 pc=0x4bccff
runtime.main()
	/usr/lib/go-1.10/src/runtime/proc.go:198 +0x212 fp=0xc42005ffe0 sp=0xc42005ff88 pc=0x42c332
runtime.goexit()
	/usr/lib/go-1.10/src/runtime/asm_amd64.s:2361 +0x1 fp=0xc42005ffe8 sp=0xc42005ffe0 pc=0x4531f1
exit status 2

```

**Comment by chai2010** [comment]
there is a bug in [`libfacedetection_capi_facedetect_rgb`](https://github.com/chai2010/libfacedetection-go/blob/master/libfacedetection_capi.cc#L19):

```c
const libfacedetection_capi_result_t* libfacedetection_capi_facedetect_rgb(
	uint8_t * rgb, int width, int height, int step
) {
	std::string sBuffer;
	sBuffer.resize(DETECT_BUFFER_SIZE);

	unsigned char* pBuffer = (unsigned char *)sBuffer.data();
	int* pResults = facedetect_cnn(pBuffer, rgb, width, height, step);
	return (libfacedetection_capi_result_t*)(pResults);
}
```

the return value pointe to the sBuffer's data, the `sBuffer` is invalid when the func returned.

**Comment by esimov** [comment]
Thanks for the quick response, but how can this be resolved?

**Comment by chai2010** [comment]
https://github.com/chai2010/libfacedetection-go/commit/83153cfa7a3034448f563aefdf908aaec5e789d1 fix the bug, u can retry the example.

**Comment by esimov** [comment]
Yes, it's working now, thanks for the fix.
